services:
  - type: web
    name: voicepm-backend
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: '["https://www.charlestobin.com", "https://editor.wix.com", "https://voicepm-backend.onrender.com"]'
    healthCheckPath: /health
    autoDeploy: true
    staticPublishPath: ./static
    envVarsIncludes: backend/.env
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80
